### ISSUE TITLE
When there are issues with the layout and arrow directions in a flowchart, there can be several common problem

### ISSUE THREAD

**Issue by shaofq** [MJaonary/vueflow-chat-flow-builder#1]
![image](https://github.com/MJaonary/vueflow-facebook-messenger/assets/28698892/92f63869-8458-4be5-aabd-51a2b923f008)

**Comment by MJaonary** [comment]
![Screenshot_20231119_205535](https://github.com/MJaonary/vueflow-facebook-messenger/assets/105315328/110975ef-b043-47af-88bf-4dd83fd44653)

Thanks for the report, I think it is fixed now.
